- The organizer becomes a carrier for the contagion of curiousity, for a people asking “why” are beginning to rebel. -Saul Alinksy
- A good tactic is one that your people enjoy. -Saul Alinksy
- Do not go gentle into that good night. Rage, rage against the dying of the light. -Dylan Thomas
- No movement is dependent on one person, and if it is, it's not a movement. -Judi Bari
- There have been tyrants and murderers and for a time they seem invincible but in the end, they always fall. -Ghandi
- Freedom is one thing. You have it all or you are not free. -MLK
- The revolution will be A/B tested. -Aaron Swartz
