inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml

AllCops:
  TargetRailsVersion: 4.2
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

### Override rubcop-github ###

Style/FrozenStringLiteralComment:
  # We aren't upgrading to Ruby 3.0, so this is just noise
  Enabled: false

Metrics/ModuleLength:
  # IME enforcing a module length creates more problems than it solves
  Enabled: false

GitHub/RailsControllerRenderLiteral:
  # Prevents us from dynamically generating layouts
  Enabled: false

GitHub/RailsControllerRenderPathsExist:
  # Doesn't seem to work; can't find templates that exist
  Enabled: false

GitHub/RailsApplicationRecord:
  # Doesn't apply to < Rails 5.0, and ignores TargetRailsVersion
  Enabled: false

Lint/Void:
  Exclude:
    - 'features/**/*'
    - 'spec/**/*'

Lint/Debugger:
  Exclude:
    - 'features/step_definitions/debug_steps.rb'

Style/BlockComments:
  Exclude:
    - 'spec/**/*'

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Security/JSONLoad:
  Enabled: true
  Exclude:
    - 'spec/**/*'
